export type Course = {
  id: string;
  code: string;
  name: string;
  credits: number;
  marks: number;
  semester: string;
  year: string;
  type: "Theory" | "Lab" | "Viva" | "Thesis";
};

export const COURSE_DATA: Course[] = [
  // Year 1, Semester 1
  {
    id: "1",
    code: "CSE1101",
    name: "Introduction to Computer System",
    credits: 2,
    marks: 50,
    semester: "1st",
    year: "Year 1",
    type: "Theory",
  },
  {
    id: "2",
    code: "CSE1102",
    name: "Structured Programming Language",
    credits: 3,
    marks: 100,
    semester: "1st",
    year: "Year 1",
    type: "Theory",
  },
  {
    id: "3",
    code: "CSE1103L",
    name: "Structured Programming Language Lab",
    credits: 2,
    marks: 50,
    semester: "1st",
    year: "Year 1",
    type: "Lab",
  },
  {
    id: "4",
    code: "MAT1104",
    name: "Math-I (Calculus)",
    credits: 3,
    marks: 100,
    semester: "1st",
    year: "Year 1",
    type: "Theory",
  },
  {
    id: "5",
    code: "PHY1105",
    name: "Physics (Electricity, Magnetism & Optics)",
    credits: 3,
    marks: 100,
    semester: "1st",
    year: "Year 1",
    type: "Theory",
  },
  {
    id: "6",
    code: "ENV1106",
    name: "Environmental Science",
    credits: 2,
    marks: 50,
    semester: "1st",
    year: "Year 1",
    type: "Theory",
  },
  {
    id: "7",
    code: "ENG1107",
    name: "English Reading Skills & Public Speaking",
    credits: 2,
    marks: 50,
    semester: "1st",
    year: "Year 1",
    type: "Theory",
  },
  {
    id: "8",
    code: "BAN1108",
    name: "Bengali",
    credits: 2,
    marks: 50,
    semester: "1st",
    year: "Year 1",
    type: "Theory",
  },
  {
    id: "9",
    code: "CSE1109",
    name: "Viva Voce",
    credits: 1,
    marks: 25,
    semester: "1st",
    year: "Year 1",
    type: "Viva",
  },

  // Year 1, Semester 2
  {
    id: "10",
    code: "CSE1201",
    name: "Object Oriented Programming Language (C++)",
    credits: 3,
    marks: 100,
    semester: "2nd",
    year: "Year 1",
    type: "Theory",
  },
  {
    id: "11",
    code: "CSE1202L",
    name: "Object Oriented Programming Language (C++) Lab",
    credits: 2,
    marks: 50,
    semester: "2nd",
    year: "Year 1",
    type: "Lab",
  },
  {
    id: "12",
    code: "EEE1203",
    name: "Electrical & Electronics Circuits",
    credits: 3,
    marks: 100,
    semester: "2nd",
    year: "Year 1",
    type: "Theory",
  },
  {
    id: "13",
    code: "EEE1204L",
    name: "Electrical & Electronics Circuits Lab",
    credits: 2,
    marks: 50,
    semester: "2nd",
    year: "Year 1",
    type: "Lab",
  },
  {
    id: "14",
    code: "CSE1205L",
    name: "Engineering Drawing and CAD Lab",
    credits: 2,
    marks: 50,
    semester: "2nd",
    year: "Year 1",
    type: "Lab",
  },
  {
    id: "15",
    code: "MAT1206",
    name: "Discrete Mathematics",
    credits: 3,
    marks: 100,
    semester: "2nd",
    year: "Year 1",
    type: "Theory",
  },
  {
    id: "16",
    code: "MAT1207",
    name: "Math-II (Co-ordinate Geometry & Vector Analysis)",
    credits: 2,
    marks: 50,
    semester: "2nd",
    year: "Year 1",
    type: "Theory",
  },
  {
    id: "17",
    code: "ENG1208",
    name: "English Writing Skills and Communications",
    credits: 2,
    marks: 50,
    semester: "2nd",
    year: "Year 1",
    type: "Theory",
  },
  {
    id: "18",
    code: "CSE1209",
    name: "Viva Voce",
    credits: 1,
    marks: 25,
    semester: "2nd",
    year: "Year 1",
    type: "Viva",
  },

  // Year 2, Semester 3
  {
    id: "19",
    code: "CSE2301",
    name: "Data Structures",
    credits: 3,
    marks: 100,
    semester: "3rd",
    year: "Year 2",
    type: "Theory",
  },
  {
    id: "20",
    code: "CSE2302L",
    name: "Data Structures Lab",
    credits: 2,
    marks: 50,
    semester: "3rd",
    year: "Year 2",
    type: "Lab",
  },
  {
    id: "21",
    code: "CSE2303",
    name: "Digital Logic & System Design",
    credits: 3,
    marks: 100,
    semester: "3rd",
    year: "Year 2",
    type: "Theory",
  },
  {
    id: "22",
    code: "CSE2304L",
    name: "Digital Logic & System Design Lab",
    credits: 2,
    marks: 50,
    semester: "3rd",
    year: "Year 2",
    type: "Lab",
  },
  {
    id: "23",
    code: "STA2305",
    name: "Statistics & Probability",
    credits: 3,
    marks: 100,
    semester: "3rd",
    year: "Year 2",
    type: "Theory",
  },
  {
    id: "24",
    code: "MAT2306",
    name: "Math-III",
    credits: 2,
    marks: 50,
    semester: "3rd",
    year: "Year 2",
    type: "Theory",
  },
  {
    id: "25",
    code: "ECO2307",
    name: "Industrial Economics",
    credits: 2,
    marks: 50,
    semester: "3rd",
    year: "Year 2",
    type: "Theory",
  },
  {
    id: "26",
    code: "PG2308",
    name: "Liberation War of Bangladesh",
    credits: 3,
    marks: 100,
    semester: "3rd",
    year: "Year 2",
    type: "Theory",
  },
  {
    id: "27",
    code: "CSE2309",
    name: "Viva Voce",
    credits: 1,
    marks: 25,
    semester: "3rd",
    year: "Year 2",
    type: "Viva",
  },

  // Year 2, Semester 4
  {
    id: "28",
    code: "CSE2401",
    name: "Algorithm",
    credits: 3,
    marks: 100,
    semester: "4th",
    year: "Year 2",
    type: "Theory",
  },
  {
    id: "29",
    code: "CSE2402L",
    name: "Algorithm Lab",
    credits: 2,
    marks: 50,
    semester: "4th",
    year: "Year 2",
    type: "Lab",
  },
  {
    id: "30",
    code: "CSE2403",
    name: "Microprocessors & Microcontrollers",
    credits: 3,
    marks: 100,
    semester: "4th",
    year: "Year 2",
    type: "Theory",
  },
  {
    id: "31",
    code: "CSE2404L",
    name: "Microcontrollers & Assembly Language Lab",
    credits: 2,
    marks: 50,
    semester: "4th",
    year: "Year 2",
    type: "Lab",
  },
  {
    id: "32",
    code: "CSE2405L",
    name: "Java Programming Language Lab",
    credits: 2,
    marks: 50,
    semester: "4th",
    year: "Year 2",
    type: "Lab",
  },
  {
    id: "33",
    code: "MAT2406",
    name: "Numerical Methods",
    credits: 2,
    marks: 50,
    semester: "4th",
    year: "Year 2",
    type: "Theory",
  },
  {
    id: "34",
    code: "MAT2407",
    name: "Math-IV",
    credits: 2,
    marks: 50,
    semester: "4th",
    year: "Year 2",
    type: "Theory",
  },
  {
    id: "35",
    code: "BBA2408",
    name: "Introduction to Management & Marketing",
    credits: 2,
    marks: 50,
    semester: "4th",
    year: "Year 2",
    type: "Theory",
  },
  {
    id: "36",
    code: "CSE2409",
    name: "Viva Voce",
    credits: 1,
    marks: 25,
    semester: "4th",
    year: "Year 2",
    type: "Viva",
  },

  // Year 3, Semester 5
  {
    id: "37",
    code: "CSE3501",
    name: "Database Management Systems",
    credits: 3,
    marks: 100,
    semester: "5th",
    year: "Year 3",
    type: "Theory",
  },
  {
    id: "38",
    code: "CSE3502L",
    name: "Database Management Systems Lab",
    credits: 2,
    marks: 50,
    semester: "5th",
    year: "Year 3",
    type: "Lab",
  },
  {
    id: "39",
    code: "CSE3503",
    name: "Computer Graphics & Animation",
    credits: 3,
    marks: 100,
    semester: "5th",
    year: "Year 3",
    type: "Theory",
  },
  {
    id: "40",
    code: "CSE3504L",
    name: "Computer Graphics & Animation Lab",
    credits: 2,
    marks: 50,
    semester: "5th",
    year: "Year 3",
    type: "Lab",
  },
  {
    id: "41",
    code: "CSE3505",
    name: "Communication Engineering",
    credits: 3,
    marks: 100,
    semester: "5th",
    year: "Year 3",
    type: "Theory",
  },
  {
    id: "42",
    code: "CSE3506",
    name: "Technical Writing & Presentation",
    credits: 2,
    marks: 50,
    semester: "5th",
    year: "Year 3",
    type: "Theory",
  },
  {
    id: "43",
    code: "CSE3507",
    name: "Computer Peripherals and Interfacing",
    credits: 3,
    marks: 100,
    semester: "5th",
    year: "Year 3",
    type: "Theory",
  },
  {
    id: "44",
    code: "BBA3508",
    name: "Financial & Managerial Accounting",
    credits: 2,
    marks: 50,
    semester: "5th",
    year: "Year 3",
    type: "Theory",
  },
  {
    id: "45",
    code: "CSE3509",
    name: "Viva Voce",
    credits: 1,
    marks: 25,
    semester: "5th",
    year: "Year 3",
    type: "Viva",
  },

  // Year 3, Semester 6
  {
    id: "46",
    code: "CSE3601",
    name: "Operating System",
    credits: 3,
    marks: 100,
    semester: "6th",
    year: "Year 3",
    type: "Theory",
  },
  {
    id: "47",
    code: "CSE3602L",
    name: "Operating System Lab",
    credits: 2,
    marks: 50,
    semester: "6th",
    year: "Year 3",
    type: "Lab",
  },
  {
    id: "48",
    code: "CSE3603",
    name: "Computer Networks & Cyber Security",
    credits: 3,
    marks: 100,
    semester: "6th",
    year: "Year 3",
    type: "Theory",
  },
  {
    id: "49",
    code: "CSE3604L",
    name: "Computer Networks & Cyber Security Lab",
    credits: 2,
    marks: 50,
    semester: "6th",
    year: "Year 3",
    type: "Lab",
  },
  {
    id: "50",
    code: "CSE3605",
    name: "Computer Architecture",
    credits: 3,
    marks: 100,
    semester: "6th",
    year: "Year 3",
    type: "Theory",
  },
  {
    id: "51",
    code: "CSE3606",
    name: "Simulation and Modeling",
    credits: 2,
    marks: 50,
    semester: "6th",
    year: "Year 3",
    type: "Theory",
  },
  {
    id: "52",
    code: "CSE3607",
    name: "Computer Ethics and Cyber Law",
    credits: 2,
    marks: 50,
    semester: "6th",
    year: "Year 3",
    type: "Theory",
  },
  {
    id: "53",
    code: "CSE3608L",
    name: "Mobile Application Lab",
    credits: 2,
    marks: 50,
    semester: "6th",
    year: "Year 3",
    type: "Lab",
  },
  {
    id: "54",
    code: "CSE3609",
    name: "Viva Voce",
    credits: 1,
    marks: 25,
    semester: "6th",
    year: "Year 3",
    type: "Viva",
  },

  // Year 4, Semester 7
  {
    id: "55",
    code: "CSE4701",
    name: "Web Design and Development",
    credits: 3,
    marks: 100,
    semester: "7th",
    year: "Year 4",
    type: "Theory",
  },
  {
    id: "56",
    code: "CSE4702L",
    name: "Web Design and Development Lab",
    credits: 2,
    marks: 50,
    semester: "7th",
    year: "Year 4",
    type: "Lab",
  },
  {
    id: "57",
    code: "CSE4703",
    name: "Software Design and Engineering",
    credits: 3,
    marks: 100,
    semester: "7th",
    year: "Year 4",
    type: "Theory",
  },
  {
    id: "58",
    code: "CSE4704L",
    name: "Software Design and Engineering Lab",
    credits: 2,
    marks: 50,
    semester: "7th",
    year: "Year 4",
    type: "Lab",
  },
  {
    id: "59",
    code: "CSE4705",
    name: "Software Project Management and QA",
    credits: 3,
    marks: 100,
    semester: "7th",
    year: "Year 4",
    type: "Theory",
  },
  {
    id: "60",
    code: "CSE4706",
    name: "Automata & Compiler Design",
    credits: 3,
    marks: 100,
    semester: "7th",
    year: "Year 4",
    type: "Theory",
  },
  {
    id: "61",
    code: "CSE4707",
    name: "Data ware-housing & Data Mining",
    credits: 3,
    marks: 100,
    semester: "7th",
    year: "Year 4",
    type: "Theory",
  },
  {
    id: "62",
    code: "CSE4708",
    name: "Viva Voce",
    credits: 1,
    marks: 25,
    semester: "7th",
    year: "Year 4",
    type: "Viva",
  },

  // Year 4, Semester 8
  {
    id: "63",
    code: "CSE4801",
    name: "Artificial Intelligence & Expert System",
    credits: 3,
    marks: 100,
    semester: "8th",
    year: "Year 4",
    type: "Theory",
  },
  {
    id: "64",
    code: "CSE4802L",
    name: "Artificial Intelligence & Expert System Lab",
    credits: 2,
    marks: 50,
    semester: "8th",
    year: "Year 4",
    type: "Lab",
  },
  {
    id: "65",
    code: "CSE4803",
    name: "Digital Signal and Image Processing",
    credits: 3,
    marks: 100,
    semester: "8th",
    year: "Year 4",
    type: "Theory",
  },
  {
    id: "66",
    code: "CSE4804L",
    name: "Digital Signal and Image Processing Lab",
    credits: 2,
    marks: 50,
    semester: "8th",
    year: "Year 4",
    type: "Lab",
  },
  {
    id: "67",
    code: "CSE4805L",
    name: "Machine Learning Lab",
    credits: 2,
    marks: 50,
    semester: "8th",
    year: "Year 4",
    type: "Lab",
  },
  {
    id: "68",
    code: "CSE4806",
    name: "IT Entrepreneurship",
    credits: 2,
    marks: 50,
    semester: "8th",
    year: "Year 4",
    type: "Theory",
  },
  {
    id: "69",
    code: "CSE4807",
    name: "Thesis/ Project Work",
    credits: 4,
    marks: 100,
    semester: "8th",
    year: "Year 4",
    type: "Thesis",
  },
  {
    id: "70",
    code: "CSE4808",
    name: "Viva Voce",
    credits: 1,
    marks: 25,
    semester: "8th",
    year: "Year 4",
    type: "Viva",
  },
];