export type ClassSession = {
    course: string;
    teacher: string;
    teacherId?: string;
    room: string;
};

export type DaySchedule = {
    day: string;
    slots: (ClassSession | null)[];
};

export type SemesterData = {
    id: string;
    label: string;
    session: string;
    credits: number;
    schedule: DaySchedule[];
};

export const routineData: Record<string, SemesterData> = {
    "8th": {
        id: "8th",
        label: "8th Semester",
        session: "July 2025",
        credits: 15,
        schedule: [
            {
                day: "Sun",
                slots: [
                    null,
                    { course: "CSE 4800", teacher: "MKN", teacherId: "101", room: "B317L" },
                    { course: "CSE 4800", teacher: "MKN", teacherId: "101", room: "B317L" },
                    null,
                    { course: "CSE 4801", teacher: "SR", teacherId: "102", room: "B315" },
                    null,
                    { course: "CSE 4803", teacher: "FT", teacherId: "103", room: "B320" },
                    null,
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    null,
                    { course: "CSE 4805", teacher: "ABC", teacherId: "104", room: "B315" },
                    { course: "CSE 4805", teacher: "ABC", teacherId: "104", room: "B315" },
                    null,
                    null,
                    null,
                    { course: "CSE 4800", teacher: "MKN", teacherId: "101", room: "B318L" },
                    { course: "CSE 4800", teacher: "MKN", teacherId: "101", room: "B318L" },
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    { course: "CSE 4801", teacher: "SR", teacherId: "102", room: "B315" },
                    null,
                    { course: "CSE 4803", teacher: "FT", teacherId: "103", room: "B320" },
                    null,
                    { course: "CSE 4807", teacher: "XYZ", teacherId: "105", room: "B322" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    null,
                    null,
                    { course: "CSE 4800", teacher: "MKN", teacherId: "101", room: "B317L" },
                    { course: "CSE 4800", teacher: "MKN", teacherId: "101", room: "B317L" },
                    { course: "CSE 4809", teacher: "BSS", teacherId: "106", room: "B320" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    { course: "CSE 4807", teacher: "XYZ", teacherId: "105", room: "B322" },
                    { course: "CSE 4809", teacher: "BSS", teacherId: "106", room: "B320" },
                    null,
                    null,
                    null,
                    null,
                    { course: "CSE 4800", teacher: "MKN", teacherId: "101", room: "B318L" },
                    { course: "CSE 4800", teacher: "MKN", teacherId: "101", room: "B318L" },
                    null,
                ],
            },
        ],
    },
    "7th": {
        id: "7th",
        label: "7th Semester",
        session: "July 2024",
        credits: 18,
        schedule: [
            {
                day: "Sun",
                slots: [
                    { course: "CSE 4701", teacher: "RH", teacherId: "107", room: "B322" },
                    { course: "CSE 4701", teacher: "RH", teacherId: "107", room: "B322" },
                    null,
                    { course: "CSE 4703", teacher: "MK", teacherId: "108", room: "B315" },
                    null,
                    null,
                    { course: "CSE 4705", teacher: "TR", teacherId: "109", room: "B321L" },
                    { course: "CSE 4705", teacher: "TR", teacherId: "109", room: "B321L" },
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    null,
                    null,
                    { course: "CSE 4707", teacher: "UF", teacherId: "110", room: "B320" },
                    null,
                    { course: "CSE 4702L", teacher: "SR", teacherId: "102", room: "B317L" },
                    null,
                    { course: "CSE 4702L", teacher: "SR", teacherId: "102", room: "B317L" },
                    null,
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    { course: "CSE 4703", teacher: "MK", teacherId: "108", room: "B315" },
                    { course: "CSE 4701", teacher: "RH", teacherId: "107", room: "B322" },
                    null,
                    null,
                    { course: "CSE 4709", teacher: "GN", teacherId: "111", room: "B316" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    null,
                    { course: "CSE 4707", teacher: "UF", teacherId: "110", room: "B320" },
                    { course: "CSE 4707", teacher: "UF", teacherId: "110", room: "B320" },
                    null,
                    { course: "CSE 4709", teacher: "GN", teacherId: "111", room: "B316" },
                    null,
                    { course: "CSE 4700", teacher: "MKN", teacherId: "101", room: "B318L" },
                    { course: "CSE 4700", teacher: "MKN", teacherId: "101", room: "B318L" },
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    null,
                    null,
                    null,
                    { course: "CSE 4700", teacher: "MKN", teacherId: "101", room: "B318L" },
                    { course: "CSE 4700", teacher: "MKN", teacherId: "101", room: "B318L" },
                    null,
                    { course: "CSE 4709", teacher: "GN", teacherId: "111", room: "B316" },
                    null,
                    null,
                ],
            },
        ],
    },
    "6th": {
        id: "6th",
        label: "6th Semester (New)",
        session: "October 2023",
        credits: 19,
        schedule: [
            {
                day: "Sun",
                slots: [
                    null,
                    null, // Moved to Tue 0 to avoid conflict with 8th Sem (MKN)
                    null, // Moved to Tue 1 to avoid conflict with 8th Sem (MKN)
                    { course: "CSE 3602L", teacher: "FT", teacherId: "103", room: "B323L" },
                    { course: "CSE 3602L", teacher: "FT", teacherId: "103", room: "B323L" },
                    null,
                    { course: "CSE 3601", teacher: "UF", teacherId: "110", room: "B315" },
                    null,
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    null,
                    null,
                    { course: "CSE 3603", teacher: "MKN", teacherId: "101", room: "B316" },
                    { course: "CSE 3608L", teacher: "SI", teacherId: "112", room: "B321L" },
                    { course: "CSE 3608L", teacher: "SI", teacherId: "112", room: "B321L" },
                    null,
                    { course: "CSE 3604L", teacher: "RM", teacherId: "113", room: "B321L" },
                    { course: "CSE 3604L", teacher: "RM", teacherId: "113", room: "B321L" },
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    { course: "CSE 3603", teacher: "MKN", teacherId: "101", room: "B322" }, // Moved from Sun
                    { course: "CSE 3603", teacher: "MKN", teacherId: "101", room: "B322" }, // Moved from Sun
                    { course: "CSE 3601", teacher: "UF", teacherId: "110", room: "B315" },
                    { course: "CSE 3605", teacher: "UF", teacherId: "110", room: "B315" },
                    null, // Moved to Slot 7 to avoid conflict with 7th Sem (GN)
                    null,
                    null,
                    { course: "CSE 3607", teacher: "GN", teacherId: "111", room: "B315" }, // Moved from Slot 4
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    { course: "CSE 3601", teacher: "UF", teacherId: "110", room: "B315" }, // Moved from Slot 2 to avoid conflict
                    null,
                    null, // Moved to Slot 0
                    null,
                    { course: "CSE 3605", teacher: "UF", teacherId: "110", room: "B315" },
                    null,
                    { course: "CSE 3606", teacher: "BSS", teacherId: "106", room: "B315" },
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    null,
                    null,
                    { course: "CSE 3606", teacher: "BSS", teacherId: "106", room: "B315" },
                    { course: "CSE 3607", teacher: "GN", teacherId: "111", room: "B315" },
                    { course: "CSE 3605", teacher: "UF", teacherId: "110", room: "B315" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
        ],
    },
    "5th": {
        id: "5th",
        label: "5th Semester (Old)",
        session: "October 2023",
        credits: 21,
        schedule: [
            {
                day: "Sun",
                slots: [
                    { course: "CSE 2501", teacher: "ABC", teacherId: "104", room: "A332" },
                    { course: "CSE 2501", teacher: "ABC", teacherId: "104", room: "A332" },
                    null,
                    null,
                    { course: "CSE 2502", teacher: "XYZ", teacherId: "105", room: "B316" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    null,
                    { course: "CSE 2503", teacher: "PQR", teacherId: "114", room: "A332" },
                    { course: "CSE 2503", teacher: "PQR", teacherId: "114", room: "A332" },
                    null,
                    { course: "CSE 2505", teacher: "LMN", teacherId: "115", room: "B316" },
                    null,
                    { course: "CSE 2507", teacher: "DEF", teacherId: "116", room: "B320" },
                    null,
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    null,
                    null,
                    { course: "CSE 2501", teacher: "ABC", teacherId: "104", room: "A332" },
                    { course: "CSE 2505", teacher: "LMN", teacherId: "115", room: "B316" },
                    null,
                    null,
                    { course: "CSE 2502L", teacher: "XYZ", teacherId: "105", room: "B317L" },
                    { course: "CSE 2502L", teacher: "XYZ", teacherId: "105", room: "B317L" },
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    { course: "CSE 2507", teacher: "DEF", teacherId: "116", room: "B320" },
                    null,
                    { course: "CSE 2503", teacher: "PQR", teacherId: "114", room: "A332" },
                    null,
                    { course: "CSE 2509", teacher: "GHI", teacherId: "117", room: "B322" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    null,
                    { course: "CSE 2509", teacher: "GHI", teacherId: "117", room: "B322" },
                    null,
                    { course: "CSE 2504L", teacher: "LMN", teacherId: "115", room: "B318L" },
                    { course: "CSE 2504L", teacher: "LMN", teacherId: "115", room: "B318L" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
        ],
    },
    "4th": {
        id: "4th",
        label: "4th Semester",
        session: "2023-2024",
        credits: 20,
        schedule: [
            {
                day: "Sun",
                slots: [
                    null,
                    { course: "CSE 2401", teacher: "SA", teacherId: "118", room: "B315" },
                    { course: "CSE 2401", teacher: "SA", teacherId: "118", room: "B315" },
                    null,
                    { course: "CSE 2403", teacher: "TB", teacherId: "119", room: "B316" },
                    null,
                    { course: "CSE 2402L", teacher: "SA", teacherId: "118", room: "B317L" },
                    { course: "CSE 2402L", teacher: "SA", teacherId: "118", room: "B317L" },
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    { course: "CSE 2405", teacher: "MC", teacherId: "120", room: "B320" },
                    { course: "CSE 2405", teacher: "MC", teacherId: "120", room: "B320" },
                    null,
                    { course: "CSE 2407", teacher: "KD", teacherId: "121", room: "B322" },
                    null,
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    null,
                    null,
                    { course: "CSE 2403", teacher: "TB", teacherId: "119", room: "B316" },
                    { course: "CSE 2401", teacher: "SA", teacherId: "118", room: "B315" },
                    null,
                    null,
                    { course: "CSE 2404L", teacher: "TB", teacherId: "119", room: "B318L" },
                    { course: "CSE 2404L", teacher: "TB", teacherId: "119", room: "B318L" },
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    { course: "CSE 2407", teacher: "KD", teacherId: "121", room: "B322" },
                    null,
                    { course: "CSE 2405", teacher: "MC", teacherId: "120", room: "B320" },
                    null,
                    { course: "CSE 2409", teacher: "JF", teacherId: "122", room: "A332" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    null,
                    { course: "CSE 2409", teacher: "JF", teacherId: "122", room: "A332" },
                    { course: "CSE 2409", teacher: "JF", teacherId: "122", room: "A332" },
                    null,
                    null,
                    null,
                    { course: "CSE 2406L", teacher: "MC", teacherId: "120", room: "B321L" },
                    { course: "CSE 2406L", teacher: "MC", teacherId: "120", room: "B321L" },
                    null,
                ],
            },
        ],
    },
    "3rd": {
        id: "3rd",
        label: "3rd Semester",
        session: "2023-2024",
        credits: 21,
        schedule: [
            {
                day: "Sun",
                slots: [
                    { course: "CSE 2301", teacher: "NK", teacherId: "123", room: "B315" },
                    { course: "CSE 2301", teacher: "NK", teacherId: "123", room: "B315" },
                    null,
                    { course: "CSE 2303", teacher: "RL", teacherId: "124", room: "B316" },
                    null,
                    null,
                    { course: "CSE 2302L", teacher: "NK", teacherId: "123", room: "B317L" },
                    { course: "CSE 2302L", teacher: "NK", teacherId: "123", room: "B317L" },
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    null,
                    null,
                    { course: "CSE 2305", teacher: "PM", teacherId: "125", room: "B320" },
                    { course: "CSE 2307", teacher: "QN", teacherId: "126", room: "B322" },
                    null,
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    { course: "CSE 2303", teacher: "RL", teacherId: "124", room: "B316" },
                    null,
                    { course: "CSE 2301", teacher: "NK", teacherId: "123", room: "B315" },
                    null,
                    { course: "CSE 2305", teacher: "PM", teacherId: "125", room: "B320" },
                    null,
                    { course: "CSE 2304L", teacher: "RL", teacherId: "124", room: "B318L" },
                    { course: "CSE 2304L", teacher: "RL", teacherId: "124", room: "B318L" },
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    null,
                    { course: "CSE 2307", teacher: "QN", teacherId: "126", room: "B322" },
                    { course: "CSE 2307", teacher: "QN", teacherId: "126", room: "B322" },
                    null,
                    { course: "CSE 2309", teacher: "SO", teacherId: "127", room: "A332" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    { course: "CSE 2309", teacher: "SO", teacherId: "127", room: "A332" },
                    null,
                    null,
                    { course: "CSE 2306L", teacher: "PM", teacherId: "125", room: "B321L" },
                    { course: "CSE 2306L", teacher: "PM", teacherId: "125", room: "B321L" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
        ],
    },
    "2nd": {
        id: "2nd",
        label: "2nd Semester",
        session: "2024-2025",
        credits: 22,
        schedule: [
            {
                day: "Sun",
                slots: [
                    null,
                    { course: "CSE 1201", teacher: "AA", teacherId: "128", room: "B315" },
                    { course: "CSE 1201", teacher: "AA", teacherId: "128", room: "B315" },
                    null,
                    { course: "EEE 1203", teacher: "BB", teacherId: "129", room: "B316" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    { course: "CSE 1205", teacher: "CC", teacherId: "130", room: "B320" },
                    null,
                    { course: "MATH 1207", teacher: "DD", teacherId: "131", room: "B322" },
                    null,
                    null,
                    null,
                    { course: "CSE 1202L", teacher: "AA", teacherId: "128", room: "B317L" },
                    { course: "CSE 1202L", teacher: "AA", teacherId: "128", room: "B317L" },
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    null,
                    null,
                    { course: "CSE 1201", teacher: "AA", teacherId: "128", room: "B315" },
                    { course: "EEE 1203", teacher: "BB", teacherId: "129", room: "B316" },
                    null,
                    null,
                    { course: "EEE 1204L", teacher: "BB", teacherId: "129", room: "B323L" },
                    { course: "EEE 1204L", teacher: "BB", teacherId: "129", room: "B323L" },
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    { course: "MATH 1207", teacher: "DD", teacherId: "131", room: "B322" },
                    { course: "MATH 1207", teacher: "DD", teacherId: "131", room: "B322" },
                    null,
                    { course: "CSE 1205", teacher: "CC", teacherId: "130", room: "B320" },
                    null,
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    null,
                    { course: "HUM 1209", teacher: "EE", teacherId: "132", room: "A332" },
                    { course: "HUM 1209", teacher: "EE", teacherId: "132", room: "A332" },
                    null,
                    { course: "CSE 1206L", teacher: "CC", teacherId: "130", room: "B318L" },
                    { course: "CSE 1206L", teacher: "CC", teacherId: "130", room: "B318L" },
                    null,
                    null,
                    null,
                ],
            },
        ],
    },
    "1st": {
        id: "1st",
        label: "1st Semester",
        session: "2024-2025",
        credits: 23,
        schedule: [
            {
                day: "Sun",
                slots: [
                    { course: "CSE 1101", teacher: "ZZ", teacherId: "133", room: "B315" },
                    { course: "CSE 1101", teacher: "ZZ", teacherId: "133", room: "B315" },
                    null,
                    { course: "PHY 1103", teacher: "YY", teacherId: "134", room: "B316" },
                    null,
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    null,
                    { course: "MATH 1105", teacher: "XX", teacherId: "135", room: "B320" },
                    { course: "MATH 1105", teacher: "XX", teacherId: "135", room: "B320" },
                    null,
                    { course: "ENG 1107", teacher: "WW", teacherId: "136", room: "B322" },
                    null,
                    { course: "CSE 1102L", teacher: "ZZ", teacherId: "133", room: "B321L" },
                    { course: "CSE 1102L", teacher: "ZZ", teacherId: "133", room: "B321L" },
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    { course: "PHY 1103", teacher: "YY", teacherId: "134", room: "B316" },
                    null,
                    { course: "CSE 1101", teacher: "ZZ", teacherId: "133", room: "B315" },
                    null,
                    null,
                    null,
                    { course: "PHY 1104L", teacher: "YY", teacherId: "134", room: "B323L" },
                    { course: "PHY 1104L", teacher: "YY", teacherId: "134", room: "B323L" },
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    null,
                    null,
                    { course: "ENG 1107", teacher: "WW", teacherId: "136", room: "B322" },
                    { course: "MATH 1105", teacher: "XX", teacherId: "135", room: "B320" },
                    null,
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    { course: "CSE 1101", teacher: "ZZ", teacherId: "133", room: "B315" },
                    null,
                    { course: "PHY 1103", teacher: "YY", teacherId: "134", room: "B316" },
                    null,
                    { course: "ENG 1108L", teacher: "WW", teacherId: "136", room: "B317L" },
                    { course: "ENG 1108L", teacher: "WW", teacherId: "136", room: "B317L" },
                    null,
                    null,
                    null,
                ],
            },
        ],
    },
};