
export type ClassSession = {
    course: string;
    teacher: string;
    room: string;
};

export type DaySchedule = {
    day: string;
    slots: (ClassSession | null)[];
};

export type SemesterData = {
    id: string;
    label: string;
    session: string;
    credits: number;
    schedule: DaySchedule[];
};

export const routineData: Record<string, SemesterData> = {
    "8th": {
        id: "8th",
        label: "8th Semester",
        session: "July 2025",
        credits: 15,
        schedule: [
            {
                day: "Sun",
                slots: [
                    null,
                    { course: "CSE 4800", teacher: "MKN", room: "Lab-1" },
                    { course: "CSE 4800", teacher: "MKN", room: "Lab-1" },
                    null,
                    { course: "CSE 4801", teacher: "SR", room: "302" },
                    null,
                    { course: "CSE 4803", teacher: "FT", room: "305" },
                    null,
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    null,
                    { course: "CSE 4805", teacher: "ABC", room: "302" },
                    { course: "CSE 4805", teacher: "ABC", room: "302" },
                    null,
                    null,
                    null,
                    { course: "CSE 4800", teacher: "MKN", room: "Lab-2" },
                    { course: "CSE 4800", teacher: "MKN", room: "Lab-2" },
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    { course: "CSE 4801", teacher: "SR", room: "302" },
                    null,
                    { course: "CSE 4803", teacher: "FT", room: "305" },
                    null,
                    { course: "CSE 4807", teacher: "XYZ", room: "301" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    null,
                    null,
                    { course: "CSE 4800", teacher: "MKN", room: "Lab-1" },
                    { course: "CSE 4800", teacher: "MKN", room: "Lab-1" },
                    { course: "CSE 4809", teacher: "BSS", room: "305" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    { course: "CSE 4807", teacher: "XYZ", room: "301" },
                    { course: "CSE 4809", teacher: "BSS", room: "305" },
                    null,
                    null,
                    null,
                    null,
                    { course: "CSE 4800", teacher: "MKN", room: "Lab-2" },
                    { course: "CSE 4800", teacher: "MKN", room: "Lab-2" },
                    null,
                ],
            },
        ],
    },
    "7th": {
        id: "7th",
        label: "7th Semester",
        session: "July 2024",
        credits: 18,
        schedule: [
            {
                day: "Sun",
                slots: [
                    { course: "CSE 4701", teacher: "RH", room: "301" },
                    { course: "CSE 4701", teacher: "RH", room: "301" },
                    null,
                    { course: "CSE 4703", teacher: "MK", room: "302" },
                    null,
                    null,
                    { course: "CSE 4705", teacher: "TR", room: "Lab-3" },
                    { course: "CSE 4705", teacher: "TR", room: "Lab-3" },
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    null,
                    null,
                    { course: "CSE 4707", teacher: "UF", room: "305" },
                    null,
                    { course: "CSE 4702L", teacher: "SR", room: "Lab-1" },
                    null,
                    { course: "CSE 4702L", teacher: "SR", room: "Lab-1" },
                    null,
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    { course: "CSE 4703", teacher: "MK", room: "302" },
                    { course: "CSE 4701", teacher: "RH", room: "301" },
                    null,
                    null,
                    { course: "CSE 4709", teacher: "GN", room: "304" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    null,
                    { course: "CSE 4707", teacher: "UF", room: "305" },
                    { course: "CSE 4707", teacher: "UF", room: "305" },
                    null,
                    { course: "CSE 4709", teacher: "GN", room: "304" },
                    null,
                    { course: "CSE 4700", teacher: "MKN", room: "Lab-2" },
                    { course: "CSE 4700", teacher: "MKN", room: "Lab-2" },
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    null,
                    null,
                    null,
                    { course: "CSE 4700", teacher: "MKN", room: "Lab-2" },
                    { course: "CSE 4700", teacher: "MKN", room: "Lab-2" },
                    null,
                    { course: "CSE 4709", teacher: "GN", room: "304" },
                    null,
                    null,
                ],
            },
        ],
    },
    "6th": {
        id: "6th",
        label: "6th Semester (New)",
        session: "October 2023",
        credits: 19,
        schedule: [
            {
                day: "Sun",
                slots: [
                    null,
                    { course: "CSE 3603", teacher: "MKN", room: "B321" },
                    { course: "CSE 3603", teacher: "MKN", room: "B321" },
                    { course: "CSE 3602L", teacher: "FT", room: "B318" },
                    { course: "CSE 3602L", teacher: "FT", room: "B318" },
                    null,
                    { course: "CSE 3601", teacher: "UF", room: "B315" },
                    null,
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    null,
                    null,
                    { course: "CSE 3603", teacher: "MKN", room: "B317" },
                    { course: "CSE 3608L", teacher: "SI", room: "B321" },
                    { course: "CSE 3608L", teacher: "SI", room: "B321" },
                    null,
                    { course: "CSE 3604L", teacher: "RM", room: "B321" },
                    { course: "CSE 3604L", teacher: "RM", room: "B321" },
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    null,
                    null,
                    { course: "CSE 3601", teacher: "UF", room: "B315" },
                    { course: "CSE 3605", teacher: "UF", room: "B315" },
                    { course: "CSE 3607", teacher: "GN", room: "B315" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    null,
                    null,
                    { course: "CSE 3601", teacher: "UF", room: "B315" },
                    null,
                    { course: "CSE 3605", teacher: "UF", room: "B315" },
                    null,
                    { course: "CSE 3606", teacher: "BSS", room: "B315" },
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    null,
                    null,
                    { course: "CSE 3606", teacher: "BSS", room: "B315" },
                    { course: "CSE 3607", teacher: "GN", room: "B315" },
                    { course: "CSE 3605", teacher: "UF", room: "B315" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
        ],
    },
    "5th": {
        id: "5th",
        label: "5th Semester (Old)",
        session: "October 2023",
        credits: 21,
        schedule: [
            {
                day: "Sun",
                slots: [
                    { course: "CSE 2501", teacher: "ABC", room: "101" },
                    { course: "CSE 2501", teacher: "ABC", room: "101" },
                    null,
                    null,
                    { course: "CSE 2502", teacher: "XYZ", room: "102" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    null,
                    { course: "CSE 2503", teacher: "PQR", room: "101" },
                    { course: "CSE 2503", teacher: "PQR", room: "101" },
                    null,
                    { course: "CSE 2505", teacher: "LMN", room: "102" },
                    null,
                    { course: "CSE 2507", teacher: "DEF", room: "103" },
                    null,
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    null,
                    null,
                    { course: "CSE 2501", teacher: "ABC", room: "101" },
                    { course: "CSE 2505", teacher: "LMN", room: "102" },
                    null,
                    null,
                    { course: "CSE 2502L", teacher: "XYZ", room: "Lab-1" },
                    { course: "CSE 2502L", teacher: "XYZ", room: "Lab-1" },
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    { course: "CSE 2507", teacher: "DEF", room: "103" },
                    null,
                    { course: "CSE 2503", teacher: "PQR", room: "101" },
                    null,
                    { course: "CSE 2509", teacher: "GHI", room: "104" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    null,
                    { course: "CSE 2509", teacher: "GHI", room: "104" },
                    null,
                    { course: "CSE 2504L", teacher: "LMN", room: "Lab-2" },
                    { course: "CSE 2504L", teacher: "LMN", room: "Lab-2" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
        ],
    },
    "4th": {
        id: "4th",
        label: "4th Semester",
        session: "2023-2024",
        credits: 20,
        schedule: [
            {
                day: "Sun",
                slots: [
                    null,
                    { course: "CSE 2401", teacher: "SA", room: "201" },
                    { course: "CSE 2401", teacher: "SA", room: "201" },
                    null,
                    { course: "CSE 2403", teacher: "TB", room: "202" },
                    null,
                    { course: "CSE 2402L", teacher: "SA", room: "Lab-A" },
                    { course: "CSE 2402L", teacher: "SA", room: "Lab-A" },
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    { course: "CSE 2405", teacher: "MC", room: "203" },
                    { course: "CSE 2405", teacher: "MC", room: "203" },
                    null,
                    { course: "CSE 2407", teacher: "KD", room: "204" },
                    null,
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    null,
                    null,
                    { course: "CSE 2403", teacher: "TB", room: "202" },
                    { course: "CSE 2401", teacher: "SA", room: "201" },
                    null,
                    null,
                    { course: "CSE 2404L", teacher: "TB", room: "Lab-B" },
                    { course: "CSE 2404L", teacher: "TB", room: "Lab-B" },
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    { course: "CSE 2407", teacher: "KD", room: "204" },
                    null,
                    { course: "CSE 2405", teacher: "MC", room: "203" },
                    null,
                    { course: "CSE 2409", teacher: "JF", room: "205" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    null,
                    { course: "CSE 2409", teacher: "JF", room: "205" },
                    { course: "CSE 2409", teacher: "JF", room: "205" },
                    null,
                    null,
                    null,
                    { course: "CSE 2406L", teacher: "MC", room: "Lab-C" },
                    { course: "CSE 2406L", teacher: "MC", room: "Lab-C" },
                    null,
                ],
            },
        ],
    },
    "3rd": {
        id: "3rd",
        label: "3rd Semester",
        session: "2023-2024",
        credits: 21,
        schedule: [
            {
                day: "Sun",
                slots: [
                    { course: "CSE 2301", teacher: "NK", room: "101" },
                    { course: "CSE 2301", teacher: "NK", room: "101" },
                    null,
                    { course: "CSE 2303", teacher: "RL", room: "102" },
                    null,
                    null,
                    { course: "CSE 2302L", teacher: "NK", room: "Lab-1" },
                    { course: "CSE 2302L", teacher: "NK", room: "Lab-1" },
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    null,
                    null,
                    { course: "CSE 2305", teacher: "PM", room: "103" },
                    { course: "CSE 2307", teacher: "QN", room: "104" },
                    null,
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    { course: "CSE 2303", teacher: "RL", room: "102" },
                    null,
                    { course: "CSE 2301", teacher: "NK", room: "101" },
                    null,
                    { course: "CSE 2305", teacher: "PM", room: "103" },
                    null,
                    { course: "CSE 2304L", teacher: "RL", room: "Lab-2" },
                    { course: "CSE 2304L", teacher: "RL", room: "Lab-2" },
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    null,
                    { course: "CSE 2307", teacher: "QN", room: "104" },
                    { course: "CSE 2307", teacher: "QN", room: "104" },
                    null,
                    { course: "CSE 2309", teacher: "SO", room: "105" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    { course: "CSE 2309", teacher: "SO", room: "105" },
                    null,
                    null,
                    { course: "CSE 2306L", teacher: "PM", room: "Lab-3" },
                    { course: "CSE 2306L", teacher: "PM", room: "Lab-3" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
        ],
    },
    "2nd": {
        id: "2nd",
        label: "2nd Semester",
        session: "2024-2025",
        credits: 22,
        schedule: [
            {
                day: "Sun",
                slots: [
                    null,
                    { course: "CSE 1201", teacher: "AA", room: "NB-1" },
                    { course: "CSE 1201", teacher: "AA", room: "NB-1" },
                    null,
                    { course: "EEE 1203", teacher: "BB", room: "NB-2" },
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    { course: "CSE 1205", teacher: "CC", room: "NB-3" },
                    null,
                    { course: "MATH 1207", teacher: "DD", room: "NB-4" },
                    null,
                    null,
                    null,
                    { course: "CSE 1202L", teacher: "AA", room: "Lab-A" },
                    { course: "CSE 1202L", teacher: "AA", room: "Lab-A" },
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    null,
                    null,
                    { course: "CSE 1201", teacher: "AA", room: "NB-1" },
                    { course: "EEE 1203", teacher: "BB", room: "NB-2" },
                    null,
                    null,
                    { course: "EEE 1204L", teacher: "BB", room: "Lab-HW" },
                    { course: "EEE 1204L", teacher: "BB", room: "Lab-HW" },
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    { course: "MATH 1207", teacher: "DD", room: "NB-4" },
                    { course: "MATH 1207", teacher: "DD", room: "NB-4" },
                    null,
                    { course: "CSE 1205", teacher: "CC", room: "NB-3" },
                    null,
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    null,
                    { course: "HUM 1209", teacher: "EE", room: "NB-5" },
                    { course: "HUM 1209", teacher: "EE", room: "NB-5" },
                    null,
                    { course: "CSE 1206L", teacher: "CC", room: "Lab-B" },
                    { course: "CSE 1206L", teacher: "CC", room: "Lab-B" },
                    null,
                    null,
                    null,
                ],
            },
        ],
    },
    "1st": {
        id: "1st",
        label: "1st Semester",
        session: "2024-2025",
        credits: 23,
        schedule: [
            {
                day: "Sun",
                slots: [
                    { course: "CSE 1101", teacher: "ZZ", room: "G-101" },
                    { course: "CSE 1101", teacher: "ZZ", room: "G-101" },
                    null,
                    { course: "PHY 1103", teacher: "YY", room: "G-102" },
                    null,
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Mon",
                slots: [
                    null,
                    { course: "MATH 1105", teacher: "XX", room: "G-103" },
                    { course: "MATH 1105", teacher: "XX", room: "G-103" },
                    null,
                    { course: "ENG 1107", teacher: "WW", room: "G-104" },
                    null,
                    { course: "CSE 1102L", teacher: "ZZ", room: "Lab-C" },
                    { course: "CSE 1102L", teacher: "ZZ", room: "Lab-C" },
                    null,
                ],
            },
            {
                day: "Tue",
                slots: [
                    { course: "PHY 1103", teacher: "YY", room: "G-102" },
                    null,
                    { course: "CSE 1101", teacher: "ZZ", room: "G-101" },
                    null,
                    null,
                    null,
                    { course: "PHY 1104L", teacher: "YY", room: "Lab-Phy" },
                    { course: "PHY 1104L", teacher: "YY", room: "Lab-Phy" },
                    null,
                ],
            },
            {
                day: "Wed",
                slots: [
                    null,
                    null,
                    { course: "ENG 1107", teacher: "WW", room: "G-104" },
                    { course: "MATH 1105", teacher: "XX", room: "G-103" },
                    null,
                    null,
                    null,
                    null,
                    null,
                ],
            },
            {
                day: "Thu",
                slots: [
                    { course: "CSE 1101", teacher: "ZZ", room: "G-101" },
                    null,
                    { course: "PHY 1103", teacher: "YY", room: "G-102" },
                    null,
                    { course: "ENG 1108L", teacher: "WW", room: "Lab-Lang" },
                    { course: "ENG 1108L", teacher: "WW", room: "Lab-Lang" },
                    null,
                    null,
                    null,
                ],
            },
        ],
    },
};