export const myRoutine = [
  {
    day: "Sat",
    time: "08:30 - 09:50",
    course: "Structured Programming",
    type: "Lecture",
    room: "B315",
    semester: "1st",
  },
  {
    day: "Sat",
    time: "10:00 - 11:20",
    course: "Physics I",
    type: "Lecture",
    room: "B315",
    semester: "1st",
  },
  {
    day: "Sat",
    time: "11:30 - 12:50",
    course: "Differential Calculus",
    type: "Lecture",
    room: "B320",
    semester: "1st",
  },
  {
    day: "Sat",
    time: "02:00 - 04:00",
    course: "Structured Programming",
    type: "Lab",
    room: "B317L",
    semester: "1st",
  },
  {
    day: "Sat",
    time: "04:10 - 05:30",
    course: "English Composition",
    type: "Lecture",
    room: "A332",
    semester: "1st",
  },
  {
    day: "Sat",
    time: "08:30 - 09:50",
    course: "Object Oriented Prog",
    type: "Lecture",
    room: "B321",
    semester: "2nd",
  },
  {
    day: "Sat",
    time: "10:00 - 11:20",
    course: "Linear Algebra",
    type: "Lecture",
    room: "B321",
    semester: "2nd",
  },
  {
    day: "Sun",
    time: "08:30 - 09:50",
    course: "Data Structures",
    type: "Lecture",
    room: "B316",
    semester: "3rd",
  },
  {
    day: "Sun",
    time: "10:00 - 11:20",
    course: "Digital Logic Design",
    type: "Lecture",
    room: "B316",
    semester: "3rd",
  },
  {
    day: "Sun",
    time: "11:30 - 12:50",
    course: "Discrete Mathematics",
    type: "Lecture",
    room: "B316",
    semester: "3rd",
  },
  {
    day: "Sun",
    time: "02:00 - 04:00",
    course: "Data Structures",
    type: "Lab",
    room: "B318L",
    semester: "3rd",
  },
  {
    day: "Sun",
    time: "04:10 - 05:30",
    course: "Statistics",
    type: "Lecture",
    room: "B419",
    semester: "3rd",
  },
  {
    day: "Sun",
    time: "08:30 - 09:50",
    course: "Algorithms",
    type: "Lecture",
    room: "A332",
    semester: "4th",
  },
  {
    day: "Sun",
    time: "10:00 - 11:20",
    course: "Database Systems",
    type: "Lecture",
    room: "A332",
    semester: "4th",
  },
  {
    day: "Sun",
    time: "02:00 - 04:00",
    course: "Database Systems",
    type: "Lab",
    room: "B321L",
    semester: "4th",
  },
  {
    day: "Mon",
    time: "08:30 - 09:50",
    course: "Computer Architecture",
    type: "Lecture",
    room: "B320",
    semester: "4th",
  },
  {
    day: "Mon",
    time: "10:00 - 11:20",
    course: "Algorithms",
    type: "Lecture",
    room: "B320",
    semester: "4th",
  },
  {
    day: "Mon",
    time: "11:30 - 12:50",
    course: "Economics",
    type: "Lecture",
    room: "B419",
    semester: "4th",
  },
  {
    day: "Mon",
    time: "02:00 - 03:20",
    course: "Software Engineering",
    type: "Lecture",
    room: "B315",
    semester: "5th",
  },
  {
    day: "Mon",
    time: "03:30 - 04:50",
    course: "Computer Networks",
    type: "Lecture",
    room: "B315",
    semester: "5th",
  },
  {
    day: "Mon",
    time: "08:30 - 11:30",
    course: "Web Technologies",
    type: "Lab",
    room: "B323L",
    semester: "5th",
  },
  {
    day: "Mon",
    time: "02:00 - 04:00",
    course: "Physics II",
    type: "Lab",
    room: "B317L",
    semester: "1st",
  },
  {
    day: "Tue",
    time: "08:30 - 09:50",
    course: "Operating Systems",
    type: "Lecture",
    room: "B316",
    semester: "5th",
  },
  {
    day: "Tue",
    time: "10:00 - 11:20",
    course: "Theory of Computing",
    type: "Lecture",
    room: "B316",
    semester: "5th",
  },
  {
    day: "Tue",
    time: "11:30 - 01:30",
    course: "Computer Networks",
    type: "Lab",
    room: "B318L",
    semester: "5th",
  },
  {
    day: "Tue",
    time: "02:00 - 03:20",
    course: "Artificial Intelligence",
    type: "Lecture",
    room: "B321",
    semester: "6th",
  },
  {
    day: "Tue",
    time: "03:30 - 04:50",
    course: "Machine Learning",
    type: "Lecture",
    room: "B321",
    semester: "6th",
  },
  {
    day: "Tue",
    time: "08:30 - 09:50",
    course: "Numerical Analysis",
    type: "Lecture",
    room: "B320",
    semester: "4th",
  },
  {
    day: "Tue",
    time: "10:00 - 12:00",
    course: "Digital Logic",
    type: "Lab",
    room: "B317L",
    semester: "3rd",
  },
  {
    day: "Wed",
    time: "08:30 - 09:50",
    course: "Compiler Design",
    type: "Lecture",
    room: "B316",
    semester: "6th",
  },
  {
    day: "Wed",
    time: "10:00 - 11:20",
    course: "Computer Graphics",
    type: "Lecture",
    room: "B316",
    semester: "6th",
  },
  {
    day: "Wed",
    time: "11:30 - 01:30",
    course: "Computer Graphics",
    type: "Lab",
    room: "B321L",
    semester: "6th",
  },
  {
    day: "Wed",
    time: "02:00 - 04:00",
    course: "Microprocessors",
    type: "Lab",
    room: "B318L",
    semester: "5th",
  },
  {
    day: "Wed",
    time: "04:10 - 05:30",
    course: "Technical Writing",
    type: "Lecture",
    room: "A332",
    semester: "6th",
  },
  {
    day: "Wed",
    time: "08:30 - 09:50",
    course: "Biology for Engineers",
    type: "Lecture",
    room: "B419",
    semester: "1st",
  },
  {
    day: "Wed",
    time: "10:00 - 11:20",
    course: "Chemistry",
    type: "Lecture",
    room: "B419",
    semester: "1st",
  },
  {
    day: "Thu",
    time: "08:30 - 09:50",
    course: "Cyber Security",
    type: "Lecture",
    room: "B321",
    semester: "7th",
  },
  {
    day: "Thu",
    time: "10:00 - 11:20",
    course: "Cloud Computing",
    type: "Lecture",
    room: "B321",
    semester: "7th",
  },
  {
    day: "Thu",
    time: "11:30 - 12:50",
    course: "Project Management",
    type: "Lecture",
    room: "B315",
    semester: "7th",
  },
  {
    day: "Thu",
    time: "02:00 - 05:00",
    course: "Final Year Project",
    type: "Lab",
    room: "B323L",
    semester: "8th",
  },
  {
    day: "Thu",
    time: "08:30 - 09:50",
    course: "Data Comm",
    type: "Lecture",
    room: "B320",
    semester: "4th",
  },
  {
    day: "Thu",
    time: "10:00 - 11:20",
    course: "Accounting",
    type: "Lecture",
    room: "B419",
    semester: "4th",
  },
  {
    day: "Thu",
    time: "02:00 - 04:00",
    course: "OOP (Java)",
    type: "Lab",
    room: "B321L",
    semester: "2nd",
  },
  {
    day: "Fri",
    time: "09:00 - 12:00",
    course: "Competitive Programming",
    type: "Lab",
    room: "B323L",
    semester: "6th",
  },
  {
    day: "Fri",
    time: "03:00 - 05:00",
    course: "Robotics Workshop",
    type: "Lab",
    room: "B317L",
    semester: "4th",
  },
  {
    day: "Fri",
    time: "08:30 - 09:50",
    course: "Executive MBA - IT",
    type: "Lecture",
    room: "B315",
    semester: "8th",
  },
  {
    day: "Fri",
    time: "10:00 - 11:20",
    course: "Supply Chain Mgmt",
    type: "Lecture",
    room: "B315",
    semester: "5th",
  },
  {
    day: "Fri",
    time: "03:00 - 04:20",
    course: "Makeup Class: Math",
    type: "Lecture",
    room: "B321",
    semester: "2nd",
  },
  {
    day: "Fri",
    time: "04:30 - 06:00",
    course: "Open Source Seminar",
    type: "Lecture",
    room: "A332",
    semester: "3rd",
  },
];