export const myRoutine = [
  {
    day: "Sat",
    time: "08:30 - 09:50",
    course: "Structured Programming",
    type: "Lecture",
    room: "R-301",
    batch: "CSE-25",
  },
  {
    day: "Sat",
    time: "10:00 - 11:20",
    course: "Physics I",
    type: "Lecture",
    room: "R-301",
    batch: "CSE-25",
  },
  {
    day: "Sat",
    time: "11:30 - 12:50",
    course: "Differential Calculus",
    type: "Lecture",
    room: "R-204",
    batch: "CSE-25",
  },
  {
    day: "Sat",
    time: "02:00 - 04:00",
    course: "Structured Programming",
    type: "Lab",
    room: "Lab-1",
    batch: "CSE-25",
  },
  {
    day: "Sat",
    time: "04:10 - 05:30",
    course: "English Composition",
    type: "Lecture",
    room: "R-402",
    batch: "CSE-25",
  },
  {
    day: "Sat",
    time: "08:30 - 09:50",
    course: "Object Oriented Prog",
    type: "Lecture",
    room: "R-201",
    batch: "CSE-24",
  },
  {
    day: "Sat",
    time: "10:00 - 11:20",
    course: "Linear Algebra",
    type: "Lecture",
    room: "R-202",
    batch: "CSE-24",
  },
  {
    day: "Sun",
    time: "08:30 - 09:50",
    course: "Data Structures",
    type: "Lecture",
    room: "R-501",
    batch: "CSE-23",
  },
  {
    day: "Sun",
    time: "10:00 - 11:20",
    course: "Digital Logic Design",
    type: "Lecture",
    room: "R-502",
    batch: "CSE-23",
  },
  {
    day: "Sun",
    time: "11:30 - 12:50",
    course: "Discrete Mathematics",
    type: "Lecture",
    room: "R-501",
    batch: "CSE-23",
  },
  {
    day: "Sun",
    time: "02:00 - 04:00",
    course: "Data Structures",
    type: "Lab",
    room: "Lab-2",
    batch: "CSE-23",
  },
  {
    day: "Sun",
    time: "04:10 - 05:30",
    course: "Statistics",
    type: "Lecture",
    room: "R-305",
    batch: "CSE-23",
  },
  {
    day: "Sun",
    time: "08:30 - 09:50",
    course: "Algorithms",
    type: "Lecture",
    room: "R-101",
    batch: "CSE-22",
  },
  {
    day: "Sun",
    time: "10:00 - 11:20",
    course: "Database Systems",
    type: "Lecture",
    room: "R-102",
    batch: "CSE-22",
  },
  {
    day: "Sun",
    time: "02:00 - 04:00",
    course: "Database Systems",
    type: "Lab",
    room: "Lab-3",
    batch: "CSE-22",
  },
  {
    day: "Mon",
    time: "08:30 - 09:50",
    course: "Computer Architecture",
    type: "Lecture",
    room: "R-205",
    batch: "CSE-22",
  },
  {
    day: "Mon",
    time: "10:00 - 11:20",
    course: "Algorithms",
    type: "Lecture",
    room: "R-205",
    batch: "CSE-22",
  },
  {
    day: "Mon",
    time: "11:30 - 12:50",
    course: "Economics",
    type: "Lecture",
    room: "R-401",
    batch: "CSE-22",
  },
  {
    day: "Mon",
    time: "02:00 - 03:20",
    course: "Software Engineering",
    type: "Lecture",
    room: "R-303",
    batch: "CSE-21",
  },
  {
    day: "Mon",
    time: "03:30 - 04:50",
    course: "Computer Networks",
    type: "Lecture",
    room: "R-303",
    batch: "CSE-21",
  },
  {
    day: "Mon",
    time: "08:30 - 11:30",
    course: "Web Technologies",
    type: "Lab",
    room: "Lab-4",
    batch: "CSE-21",
  },
  {
    day: "Mon",
    time: "02:00 - 04:00",
    course: "Physics II",
    type: "Lab",
    room: "Phy-Lab",
    batch: "CSE-25",
  },
  {
    day: "Tue",
    time: "08:30 - 09:50",
    course: "Operating Systems",
    type: "Lecture",
    room: "R-601",
    batch: "CSE-21",
  },
  {
    day: "Tue",
    time: "10:00 - 11:20",
    course: "Theory of Computing",
    type: "Lecture",
    room: "R-601",
    batch: "CSE-21",
  },
  {
    day: "Tue",
    time: "11:30 - 01:30",
    course: "Computer Networks",
    type: "Lab",
    room: "Lab-Network",
    batch: "CSE-21",
  },
  {
    day: "Tue",
    time: "02:00 - 03:20",
    course: "Artificial Intelligence",
    type: "Lecture",
    room: "R-404",
    batch: "CSE-20",
  },
  {
    day: "Tue",
    time: "03:30 - 04:50",
    course: "Machine Learning",
    type: "Lecture",
    room: "R-404",
    batch: "CSE-20",
  },
  {
    day: "Tue",
    time: "08:30 - 09:50",
    course: "Numerical Analysis",
    type: "Lecture",
    room: "R-208",
    batch: "CSE-22",
  },
  {
    day: "Tue",
    time: "10:00 - 12:00",
    course: "Digital Logic",
    type: "Lab",
    room: "Lab-HW",
    batch: "CSE-23",
  },
  {
    day: "Wed",
    time: "08:30 - 09:50",
    course: "Compiler Design",
    type: "Lecture",
    room: "R-505",
    batch: "CSE-20",
  },
  {
    day: "Wed",
    time: "10:00 - 11:20",
    course: "Computer Graphics",
    type: "Lecture",
    room: "R-505",
    batch: "CSE-20",
  },
  {
    day: "Wed",
    time: "11:30 - 01:30",
    course: "Computer Graphics",
    type: "Lab",
    room: "Lab-Multimedia",
    batch: "CSE-20",
  },
  {
    day: "Wed",
    time: "02:00 - 04:00",
    course: "Microprocessors",
    type: "Lab",
    room: "Lab-HW",
    batch: "CSE-21",
  },
  {
    day: "Wed",
    time: "04:10 - 05:30",
    course: "Technical Writing",
    type: "Lecture",
    room: "R-105",
    batch: "CSE-20",
  },
  {
    day: "Wed",
    time: "08:30 - 09:50",
    course: "Biology for Engineers",
    type: "Lecture",
    room: "R-109",
    batch: "CSE-25",
  },
  {
    day: "Wed",
    time: "10:00 - 11:20",
    course: "Chemistry",
    type: "Lecture",
    room: "R-109",
    batch: "CSE-25",
  },
  {
    day: "Thu",
    time: "08:30 - 09:50",
    course: "Cyber Security",
    type: "Lecture",
    room: "R-602",
    batch: "CSE-19",
  },
  {
    day: "Thu",
    time: "10:00 - 11:20",
    course: "Cloud Computing",
    type: "Lecture",
    room: "R-602",
    batch: "CSE-19",
  },
  {
    day: "Thu",
    time: "11:30 - 12:50",
    course: "Project Management",
    type: "Lecture",
    room: "R-305",
    batch: "CSE-19",
  },
  {
    day: "Thu",
    time: "02:00 - 05:00",
    course: "Final Year Project",
    type: "Lab",
    room: "Project-Lab",
    batch: "CSE-19",
  },
  {
    day: "Thu",
    time: "08:30 - 09:50",
    course: "Data Comm",
    type: "Lecture",
    room: "R-201",
    batch: "CSE-22",
  },
  {
    day: "Thu",
    time: "10:00 - 11:20",
    course: "Accounting",
    type: "Lecture",
    room: "R-402",
    batch: "CSE-22",
  },
  {
    day: "Thu",
    time: "02:00 - 04:00",
    course: "OOP (Java)",
    type: "Lab",
    room: "Lab-2",
    batch: "CSE-24",
  },
  {
    day: "Fri",
    time: "09:00 - 12:00",
    course: "Competitive Programming",
    type: "Lab",
    room: "Lab-1",
    batch: "Club",
  },
  {
    day: "Fri",
    time: "03:00 - 05:00",
    course: "Robotics Workshop",
    type: "Lab",
    room: "Lab-Robo",
    batch: "Club",
  },
  {
    day: "Fri",
    time: "08:30 - 09:50",
    course: "Executive MBA - IT",
    type: "Lecture",
    room: "R-VIP",
    batch: "EMBA",
  },
  {
    day: "Fri",
    time: "10:00 - 11:20",
    course: "Supply Chain Mgmt",
    type: "Lecture",
    room: "R-VIP",
    batch: "EMBA",
  },
  {
    day: "Fri",
    time: "03:00 - 04:20",
    course: "Makeup Class: Math",
    type: "Lecture",
    room: "R-201",
    batch: "CSE-24",
  },
  {
    day: "Fri",
    time: "04:30 - 06:00",
    course: "Open Source Seminar",
    type: "Lecture",
    room: "Auditorium",
    batch: "All",
  },
] as const;